In [33]:
import pandas as pd

m=0.849
b=1.504
value_x_list = [1, 2, 2, 3,4,4,5,6]
value_y_list = [2, 3, 4, 4,4,6,5,7]
data= {"x": value_x_list, "y": value_y_list}
df = pd.DataFrame(data)
df
df['product_ypred'] = m*df['x'] + b
df

   x  y  product_ypred
0  1  2          2.353
1  2  3          3.202
2  2  4          3.202
3  3  4          4.051
4  4  4          4.900
5  4  6          4.900
6  5  5          5.749
7  6  7          6.598

In [34]:
df['y-ypred'] = df['y'] - df['product_ypred']
df

   x  y  product_ypred  y-ypred
0  1  2          2.353   -0.353
1  2  3          3.202   -0.202
2  2  4          3.202    0.798
3  3  4          4.051   -0.051
4  4  4          4.900   -0.900
5  4  6          4.900    1.100
6  5  5          5.749   -0.749
7  6  7          6.598    0.402

In [36]:
df['y-ypred'] = df['product_ypred'] - df['y']
df

   x  y  product_ypred  y-ypred
0  1  2          2.353    0.353
1  2  3          3.202    0.202
2  2  4          3.202   -0.798
3  3  4          4.051    0.051
4  4  4          4.900    0.900
5  4  6          4.900   -1.100
6  5  5          5.749    0.749
7  6  7          6.598   -0.402

To calculate the **Standard Error of the Residuals** (also known as the Residual Standard Error) for your table, we use the following formula:

$$\text{Standard Error} = \sqrt{\frac{\sum (y_i - \hat{y}_i)^2}{n - k}}$$

Where:
- $y_i$ is the actual observed value.
- $\hat{y}_i$ is the predicted value from the regression model (which is `product_ypred` in your table).
- $(y_i - \hat{y}_i)$ are the residuals (your `y-ypred` column).
- $n$ is the number of data points.
- $k$ is the number of regression coefficients estimated (in simple linear regression, $k=2$ for the slope $m$ and the intercept $b$).

Let's calculate this using the `y-ypred` column.

In [37]:
n = len(df) # Number of data points
sum_of_squared_residuals = (df['y-ypred']**2).sum()
k = 2 # Number of coefficients (m and b) in simple linear regression

standard_error_of_residuals = (sum_of_squared_residuals / (n - k))**0.5

print(f"The Standard Error of the Residuals for the table is: {standard_error_of_residuals:.3f}")

The Standard Error of the Residuals for the table is: 0.769